-- Persistent engagement counters used by Library detail and Discover.
create table if not exists public.library_stars (
  library_id uuid not null references public.libraries(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (library_id, user_id)
);

create table if not exists public.library_downloads (
  id bigint generated by default as identity primary key,
  library_id uuid not null references public.libraries(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists library_stars_library_id_idx
  on public.library_stars(library_id);

create index if not exists library_downloads_library_id_idx
  on public.library_downloads(library_id);

alter table public.library_stars enable row level security;
alter table public.library_downloads enable row level security;
